default:
  image: python:3.10-bookworm
  tags:
    - linux_docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  script:
    - pip install -U .[dev]
    - tox run -f test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

pages:
  stage: deploy
  script:
    - pip install -U .[dev]
    - tox run -e docs
    - mkdir -p public && cp -a docs/build/html/* public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
