name: Build and publish

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install Python 3.10
      run: uv python install 3.10

    - name: Build
      run: uvx --from 'tox==4.21.*' --with 'tox-uv==1.16.*' tox -e build

    - uses: actions/upload-artifact@v4
      with:
        name: buildresult
        path: ./dist/*

  upload_pypi_test:
    name: Upload to PyPi (Test)
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: buildresult
          path: dist

      - name: Publish to PyPi (test)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  upload_pypi:
    name: Upload to PyPi
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: buildresult
          path: dist

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
