name: Lint and test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'releases/**'
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10 & 3.11
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.10
          3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]

    - name: Lint
      run: |
        tox -e lint

    - name: Test with pytest
      run: |
        tox -f test

    - uses: actions/upload-artifact@v4
      with:
        name: Test Report
        path: ./reports/*
